"""Added created_at in order table

Revision ID: 07f97fe0b6dc
Revises: 0c90f9e22f2a
Create Date: 2025-04-14 16:41:20.881361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07f97fe0b6dc'
down_revision = '0c90f9e22f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.create_table('inventory',
    sa.Column('stock_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reorder_level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
