"""change order_item__id to product_id in inventory table

Revision ID: 0c90f9e22f2a
Revises: b31848c06a63
Create Date: 2025-04-12 23:37:03.314321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c90f9e22f2a'
down_revision = 'b31848c06a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.drop_column('order_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
