"""change item_name to product_name in inventory table

Revision ID: 4661b1aca9db
Revises: 8d37840347fc
Create Date: 2025-04-12 23:14:12.392475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4661b1aca9db'
down_revision = '8d37840347fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
