"""Added totatl_cost_price and profit in order table

Revision ID: 57ed75111d50
Revises: 07f97fe0b6dc
Create Date: 2025-04-14 16:45:49.238816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ed75111d50'
down_revision = '07f97fe0b6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('profit', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('profit')
        batch_op.drop_column('total_cost_price')

    # ### end Alembic commands ###
