"""change quantity to stock_quantity in inventory

Revision ID: 684a0d485fb9
Revises: bd017608f50d
Create Date: 2025-04-29 17:58:20.475952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '684a0d485fb9'
down_revision = 'bd017608f50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=True))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###
