"""change id to product_id in inventory table

Revision ID: bd017608f50d
Revises: 7d45136bff5f
Create Date: 2025-04-14 21:34:23.034592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd017608f50d'
down_revision = '7d45136bff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
