"""Add supplier_id to products

Revision ID: e5ddfdffe6ec
Revises: d9a6da2306c3
Create Date: 2025-04-30 00:13:54.922827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ddfdffe6ec'
down_revision = 'd9a6da2306c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'supplier', ['supplier_id'], ['supplier_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
